### PR TITLE
Added Rticles hex

### PR DESCRIPTION
**Pull request by drjuliejung**
* [x ] I have converted fonts to outlines in the `.svg`
* [x ] My PNG has dimensions 2521 x 2911

### CODE REVIEW

**Comment by hadley** [comment]
@cderv do you mind looking at the action again?

**Comment by cderv** [comment]
Sure, I'll look into it closer. 
Not obvious to me right now why the pr-push action does not manage to commit to this forked branch. 

I'll have a look, after my time off if that is ok, and fix the workflow.

**Comment by hadley** [comment]
Yeah, no rush. Just whenever you have some time.

**Comment by cderv** [comment]
@hadley the PR comment works to render a README.md to see how it looks like. 

I did not manage to update the commit status to have a green tick, or add the rebuild as a check. Anyway, we can now build README.Rmd on PR. 

I will let you merge as I am not sure what exactly needs to be check for each hex addition.

**Pull request merged**
