### PR TITLE
New PR for Distill hex

### PR DESCRIPTION
**Pull request by drjuliejung**
* [x ] I have converted fonts to outlines in the `.svg`
* [x ] My PNG has dimensions 2521 x 2911

### CODE REVIEW

**Comment by cderv** [comment]
Hi @drjuliejung, 
I tried a new workflow on this PR to build the README.md from the PR directly. I saw that this is like #49. Should we keep this PR only ? 

Thanks

**Comment by drjuliejung** [comment]
I think we should close #49 and use this PR #61. I am hoping that this PR doesn't have the same viewbox issue in the svg as before. Thank you!

**Pull request merged**
