### PR TITLE
Update plumber logo

### PR DESCRIPTION
**Pull request by blairj09**
Remove previous plumber logo and add new one.
Closes https://github.com/rstudio/plumber/issues/613

### CODE REVIEW

**Comment by schloerke** [comment]
@blairj09 Does the PNG have the size 2206 x 2557?

Readme.md: 
> A .png in the PNG directory (with dimensions 2206 x 2557).

**Comment by blairj09** [comment]
@schloerke I adjusted the PNG size and it's currently 2206 x 2547, so 10 pixels off 😬

**Comment by schloerke** [comment]
@allisonhorst Do you know why the plumber logo doesn't scale to the preferred size? ...kinda fun to look at the onion skin view of [`915ef41` (#29)](https://github.com/rstudio/hex-stickers/pull/29/commits/915ef41ec9bffec44f72b8702aafebca4540c98a?short_path=eda3a93#diff-eda3a931dfa507613e1466e014488275) 

Just want to make sure I didn't do something odd and we conform like the other logos.  Thank you!!

**Comment by allisonhorst** [comment]
No idea & I'm curious about this too. Whenever I rescale, starting from a perfect hexagon, they're always 2206 x 2547. I wonder if @gregswinehart has the answer?

**Comment by hadley** [comment]
@schloerke is this now the right size?

**Pull request merged**
