### PR TITLE
Add connectapi, miniCRAN, rstudioapi, sss, sortable, and rrd

### PR DESCRIPTION
**Pull request by andrie**

### CODE REVIEW

**Comment by hadley** [comment]
`rsconnect.png` seems to have a bunch of whitespace around it, and the text in the svgs isn't rendering for me — you may need to convert text to outlines.

**Comment by andrie** [comment]
Thank you for catching this.  I'm fixing.

**Comment by hadley** [comment]
The problem with missing text appears in many of the svgs, not just rsconnect.

**Comment by andrie** [comment]
Thanks for catching again.  I've now installed an svg previewer so I can detect these problems myself.  I've modified all the logos to use only unflowed text (this seems to have been the root cause).  I have now checked that these svg images render properly in a browser and in preview.

**Comment by hadley** [comment]
I think you still need to convert text to oulines — this is what I see when I preview the rsconnect logo on GitHub:

Screenshot 2019-12-13 at 7 14 25 AM

**Comment by hadley** [comment]
Sorry, didn't mean to close this!

**Comment by andrie** [comment]
I have updated all of the SVG files, after converting the text to vector paths.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
