### PR TITLE
New logos for baguette, discrim, embed, rules

### PR DESCRIPTION
**Pull request by veeps**
* [ x] I have converted fonts to outlines in the `.svg`
* [ x] My PNG has dimensions 2206 x 2557

### CODE REVIEW

**Comment by topepo** [comment]
Can you update from `rstudio:master`? There is a file or two missing.

**Comment by veeps** [comment]
Just saw this notification... I did a pull upstream. Did that work?

**Comment by topepo** [comment]
It didn't. The commit has 

> This commit does not belong to any branch on this repository.

At this point, the safest thing to do would be to save the new hex files somewhere, delete your repo, re-fork `rstudio/hex-stickers`, and do another PR.

**Comment by hadley** [comment]
@topepo I'm not seeing what you're seeing; this branch looks fine to me.

**Comment by topepo** [comment]
So it is ready to merge?

**Comment by hadley** [comment]
Can we wait a week? We might be tweaking the size of the PNGs going forward

**Comment by topepo** [comment]
No hurry

**Comment by cderv** [comment]
Hi, 

Just some context: I just rebuilt the README using the new GHA workflow that work for PR from fork. it was a way to test the workflow was working fine too.

**Comment by hadley** [comment]
I'm going to close this PR momentarily because we're changing the default branch from master to main, but it would be great to get these finished off and into the repo. @veeps  there's been two changes in the 2 years (eeek!) since you started this PR — we've changed the png size to 2521 x 2911 and we no longer include the url on the stickers (since (a) our name changed and (b) it was impossible to read on the stickers anyway). Do you have time to make those updates?

**Pull request closed without merging**
