### PR TITLE
Add googlesheets4 logo

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by jennybc** [comment]
@allisonhorst Do you see how the SVG displays? As if it is on a very tall canvas (apologies for my wording). Does that look correct to you?

**Comment by jennybc** [comment]
@allisonhorst In fact, the font doesn't look right on the SVG either 🤔

**Comment by hadley** [comment]
Key phrase is "convert fonts to outlines"

**Comment by jennybc** [comment]
Amending my comments on the SVG: the immediate square around the hex also does not appear to be transparent.

**Comment by jennybc** [comment]
I think this is good to go.

**Pull request merged**
