### PR TITLE
added new hex design for stacks

### PR DESCRIPTION
**Pull request by drjuliejung**
* [x] I have converted fonts to outlines in the `.svg`
* [x] My PNG has dimensions 2521 x 2911

### CODE REVIEW

**Comment by jamjulie** [comment]
Hello! I have added 2 new files. Would it be possible to merge these changes? @hadley @apreshill

**Comment by hadley** [comment]
@jamjulie is this somehow blocking you? Usually we wait until there are a number of stickers to merge.

**Comment by jamjulie** [comment]
@hadley Ok great! It's just that the readme failed to render and I'm not sure if that's an issue... I'd be happy to put in another pull request if needed. Otherwise I'll just leave this PR be. Thank you!

**Pull request merged**
