### PR TITLE
Add duckplyr logos 

### PR DESCRIPTION
**Pull request by luisDVA**
Added duckplyr logos, trimmed the hi-res source materials from [duckplyr issue #249 ](https://github.com/tidyverse/duckplyr/issues/249) to hex using the proper dimensions

* [x ] I have converted fonts to outlines in the `.svg`
* [ x] My PNG has dimensions 2521 x 2911

### CODE REVIEW

**Comment by hadley** [comment]
We'll need to get permission from duckdb to include that logo here, since everything here is licensed as CC0.

**Comment by hannes** [comment]
You have permission

**Comment by hadley** [comment]
Thanks @hannes!

**Pull request merged**
