### PR TITLE
Add R6 hex logo

### PR DESCRIPTION
**Pull request by wch**
Going retro-futuristic for R6.

R6

### CODE REVIEW

**Comment by hadley** [comment]
Can you please convert fonts to outlines?

**Comment by wch** [comment]
Updated version:
R6-8-small

**Comment by wch** [comment]
Now with a black background.

r6-10-small

**Comment by hadley** [comment]
Looks good! I assume you'll ping me when you're sure you have the final version.

**Comment by wch** [comment]
R6-11-small

**Pull request merged**
